name: single_image_small

defaults:
  - data: CIFAR10
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
  - _self_
model: vit_custom

user:
  provide_labels: False
  num_data_points: 1

# Server and user:
num_queries: 1
