defaults:
  - _default_optimization_attack
  - _self_
type: gradvit
label_strategy: yin

objective:
  type: cosine-similarity
  scale: 1e-1 # need to have a much smaller scale like 0.0001 for euclidean objectives

restarts:
  num_trials: 3
  scoring: "cosine-similarity"

optim:
  optimizer: adam
  signed:
  step_size: 0.1
  boxed: False
  max_iterations: 20_000
  step_size_decay: cosine-decay

  callback: 1000 # Print objective value every callback many iterations

regularization:
  image_prior:
    scale: 0.2
    max_iters: 20_000
    first_bn_multiplier: 1.0
  patch_prior:
    scale: 1e-1
    patch_size: 14
  total_variation:
    scale: 0.1
    inner_exp: 2
    outer_exp: 0.5
    double_opponents: True
  norm:
    scale: 0.1
    pnorm: 2
  group_regularization:
    parallel: True
    scale: 0.01
    warmup_iters: 2000
    


