defaults:
  - _default_optimization_attack
  - _self_
type: invertinggradients
label_strategy: yin

objective:
  type: euclidean
  scale: 4e-3 # need to have a much smaller scale like 0.0001 for euclidean objectives

restarts:
  num_trials: 1
  scoring: "euclidean"

optim:
  optimizer: adam
  signed:
  step_size: 0.1
  boxed: True
  max_iterations: 120_000
  step_size_decay: step-lr

  callback: 1000 # Print objective value every callback many iterations

regularization:
  total_variation:
    scale: 1e-4
    # 0.2 # The old version did not take the mean dx + dy as the new version, so this corresponds to 0.1 in the old repo
    inner_exp: 1
    outer_exp: 1
  norm:
    scale: 1e-4
    pnorm: 2
  image_prior:
    scale: 0.2
  patch_prior:
    scale: 1e-4
    patch_size: 14
  # group_regularization: # Not implemented.
  #  scale: 0.01


